version: "3.3"
services: 
    web:
        user: "${UID}:${GID}"
        build: web/.
        ports: 
            - 8888:8080
        volumes:
            - ./web/logs:/usr/local/tomcat/logs
            - ../HanSolo/target/HanSolo.war:/usr/local/tomcat/webapps/HanSolo.war